version: '3.1'
services:
  backend:
    restart: always
    container_name: backend
    build:
      context: D:\proyectos\piloto_sistema_backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000